[33m7840044[m[33m ([m[1;36mHEAD -> [m[1;32midentity-and-further[m[33m, [m[1;31morigin/identity-and-further[m[33m)[m HEAD@{0}: checkout: moving from master to identity-and-further
[33mccbfd30[m[33m ([m[1;32mmaster[m[33m)[m HEAD@{1}: reset: moving to ccbfd3003771ffadb269df29b14d4f10da936d5d
[33m5583496[m HEAD@{2}: reset: moving to 5583496730e540f08a48f3c05b65ef62b8d727ad
[33m0b0b05b[m[33m ([m[1;31morigin/master[m[33m)[m HEAD@{3}: reset: moving to 0b0b05babdbb65fde1f881c122b09fce450185f7
[33m1a9506b[m HEAD@{4}: reset: moving to 1a9506b97b6bf5cb6e29b713b248f93603799bc2
[33me1171dd[m HEAD@{5}: checkout: moving from identity-and-further to master
[33m7840044[m[33m ([m[1;36mHEAD -> [m[1;32midentity-and-further[m[33m, [m[1;31morigin/identity-and-further[m[33m)[m HEAD@{6}: checkout: moving from master to identity-and-further
[33me1171dd[m HEAD@{7}: commit: new commit after identity
[33m1a9506b[m HEAD@{8}: commit: added identity and also a home page view model
[33m6891110[m HEAD@{9}: commit: identity started and some small changes in nugget packages
[33m7840044[m[33m ([m[1;36mHEAD -> [m[1;32midentity-and-further[m[33m, [m[1;31morigin/identity-and-further[m[33m)[m HEAD@{10}: reset: moving to 78400444ab4fb68f963cd2d919ce4949a52e4878
[33m5583496[m HEAD@{11}: reset: moving to 5583496730e540f08a48f3c05b65ef62b8d727ad
[33m7840044[m[33m ([m[1;36mHEAD -> [m[1;32midentity-and-further[m[33m, [m[1;31morigin/identity-and-further[m[33m)[m HEAD@{12}: reset: moving to 78400444ab4fb68f963cd2d919ce4949a52e4878
[33m5825199[m HEAD@{13}: reset: moving to 5825199
[33m0b0b05b[m[33m ([m[1;31morigin/master[m[33m)[m HEAD@{14}: commit: er
[33m5583496[m HEAD@{15}: reset: moving to 5583496730e540f08a48f3c05b65ef62b8d727ad
[33m5825199[m HEAD@{16}: reset: moving to HEAD
[33m5825199[m HEAD@{17}: reset: moving to 5825199
[33mdc9ea2d[m HEAD@{18}: commit: check reset
[33m5825199[m HEAD@{19}: reset: moving to 5825199
[33m8b666f6[m HEAD@{20}: revert: Revert "addition to the previous"
[33m5747559[m HEAD@{21}: commit: random commit
[33md3d682f[m HEAD@{22}: checkout: moving from qOptions to master
[33m5825199[m HEAD@{23}: reset: moving to 5825199ccb8363d562605e5a6ccc7cc6d3410e6d
[33m04cbfef[m HEAD@{24}: commit: call back previous version of qoptions
[33m5825199[m HEAD@{25}: reset: moving to 5825199ccb8363d562605e5a6ccc7cc6d3410e6d
[33m04655e2[m[33m ([m[1;31morigin/qOptions[m[33m)[m HEAD@{26}: commit: check checkout
[33me0e3f27[m HEAD@{27}: checkout: moving from e0e3f27fb89dbc0cf15ddc48fe517e1e682476d1 to qOptions
[33me0e3f27[m HEAD@{28}: revert: Revert "addition to the previous"
[33md3d682f[m HEAD@{29}: checkout: moving from master to d3d682f541279268fecdbe06dd6c1783488e4457
[33md3d682f[m HEAD@{30}: cherry-pick: addition to the previous
[33m5583496[m HEAD@{31}: commit: previous datatable commit final
[33mccbfd30[m[33m ([m[1;32mmaster[m[33m)[m HEAD@{32}: commit: rough implementation of datatable
[33m7840044[m[33m ([m[1;36mHEAD -> [m[1;32midentity-and-further[m[33m, [m[1;31morigin/identity-and-further[m[33m)[m HEAD@{33}: commit: fixed some bugs with the ordering and finalized it
[33m41bef69[m HEAD@{34}: commit: All order by added successfully final
[33m4cc0601[m HEAD@{35}: commit: All Order by added successfully
[33m33037d0[m HEAD@{36}: commit: Added and checked all the Question Order set and function in Question Model
[33m5825199[m HEAD@{37}: commit: addition to the previous
[33mb55ea30[m HEAD@{38}: commit: Condition for viewing the options or not is added in question section and java script is also added for the same to be executed
[33m695bc83[m HEAD@{39}: commit: completion of raw project
[33me69563f[m HEAD@{40}: commit: first commit of the day
[33me08a33b[m HEAD@{41}: commit: made some sticky changes to layout
[33mbda2491[m HEAD@{42}: commit (initial): initial commit after reinstall
